import { IconAnoComponent } from "./IconAno";
import { IconAssentosComponent } from "./IconAssentos";
import { IconAutonomiaComponent } from "./IconAutonomia";
import { IconCambioComponent } from "./IconCambio";
import { IconCarroceriaComponent } from "./IconCarroceria";
import { IconCombustivelComponent } from "./IconCombustivel";
import { IconConfortoComponent } from "./IconConforto";
import { IconCorComponent } from "./IconCor";
import { IconDocumentationComponent } from "./IconDocumentation";
import { IconEssenciaisComponent } from "./IconEssenciais";
import { IconKMComponent } from "./IconKM";
import { IconMarcaComponent } from "./IconMarca";
import { IconOpcionaisComponent } from "./IconOpcionais";
import { IconPlacaComponent } from "./IconPlaca";
import { IconPortasComponent } from "./IconPortas";
import { IconPotenciaComponent } from "./IconPotencia";
import { IconPrecoComponent } from "./IconPreco";
import { IconSegurancaComponent } from "./IconSeguranca";
import { IconTecnologiaComponent } from "./IconTecnologia";
import { IconTracaoComponent } from "./IconTracao";

export const IconAno = IconAnoComponent;
export const IconPreco = IconPrecoComponent;
export const IconKM = IconKMComponent;
export const IconCarroceria = IconCarroceriaComponent;
export const IconOpcionais = IconOpcionaisComponent;
export const IconMarca = IconMarcaComponent;
export const IconCambio = IconCambioComponent;
export const IconCombustivel = IconCombustivelComponent;
export const IconCor = IconCorComponent;
export const IconDocumentation = IconDocumentationComponent;
export const IconPotencia = IconPotenciaComponent;
export const IconPortas = IconPortasComponent;
export const IconTracao = IconTracaoComponent;
export const IconAutonomia = IconAutonomiaComponent;
export const IconPlaca = IconPlacaComponent;
export const IconAssentos = IconAssentosComponent;
export const IconTecnologia = IconTecnologiaComponent;
export const IconSeguranca = IconSegurancaComponent;
export const IconConforto = IconConfortoComponent;
export const IconEssenciais = IconEssenciaisComponent;
